### ISSUE TITLE
Cannot delete agency

### ISSUE THREAD

**Issue by mattwigway** [conveyal/gtfs-editor#115]
Clicking delete agency makes it disappear, but it reappears when you refresh the page.

**Comment by mattwigway** [comment]
I think this should be fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with). Feel free to reopen if it isn't.

**Comment by landonreed** [comment]
Woot!!! :fireworks: 

Thanks @mattwigway!  I'll check it out today.

**Comment by landonreed** [comment]
@mattwigway I'm getting the following error when I try to `play run`.

I'm running on a mac with play 1.2.5.3, a setup had previously worked.  I reset the `application.conf` file and tried to run `play clean` but still no luck.

```
Compilation error (In /app/controllers/api/AgencyController.java around line 1)
The file /app/controllers/api/AgencyController.java could not be compiled. Error raised is : The package controllers.api collides with a type

play.exceptions.CompilationException: The package controllers.api collides with a type
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
	at play.Play.start(Play.java:516)
	at play.Play.detectChanges(Play.java:630)
	at play.Invoker$Invocation.init(Invoker.java:198)
	at Invocation.HTTP Request(Play!)
```

**Comment by landonreed** [comment]
@mattwigway maybe this has something to do with missing dependencies in lib??

**Comment by mattwigway** [comment]
I think this was because there was a class controllers.Api and a package controllers.api. Some JVMs may not be case sensitive. Try now?

**Comment by landonreed** [comment]
Yep, that did the trick!
